site:
  title: RISC-V Ratified Specifications Library
  url: https://docs.riscv.org
  keys:
    # google_analytics: 'GTM-NXLCGZF4'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''

output:
  dir: ./build/reference

content:
  sources:
  - url: https://github.com/riscv/riscv-aia.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /
    worktrees: true
    submodules: true

  - url: https://github.com/riscv-non-isa/riscv-iommu.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /
    worktrees: true
    submodules: true

  - url: https://github.com/riscv/riscv-plic-spec.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/server-soc.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

#   - url: https://github.com/riscv/docs-dev-guide.git
#     branches: [version25,antora-redo]
#     start_page: ROOT::index.adoc
#     start_path: /
#     worktrees: true
#     submodules: true

  - url: https://github.com/riscv/riscv-isa-manual.git
     #branches: [main,v20250508,v20240411]
    branches: [v20250508,v20240411]
    start_page: ROOT::index.adoc
    start_path: /
     # Enable symlink resolution
    worktrees: true
    submodules: true

  - url: https://github.com/riscv-non-isa/riscv-trace-spec.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-cbqri.git
    branches: antora-refactor
    start_page: ROOT::intro.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-ras-eri.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/e-trace-encap.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

#  - url: https://github.com/riscv-non-isa/tg-nexus-trace.git
#    branches: antora-refactor
#    start_path: modules/ntrace

#  - url: https://github.com/riscv-non-isa/tg-nexus-trace.git
#    branches: antora-refactor
#    start_path: modules/connectors

#  - url: https://github.com/riscv-non-isa/tg-nexus-trace.git
#    branches: antora-refactor
#    start_path: modules/tci

# Leaving this one commented out as it needs to be broken into chapters and appendices.
#  - url: https://github.com/riscv-non-isa/riscv-acpi-ffh.git
#    branches: antora-refactor
#    start_page: ROOT::index.adoc
#    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-semihosting.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-brs.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-acpi-rimt.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-rpmi.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-sbi-doc.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-uefi.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  # NOTE: the HTML does not match the PDF, but in this case, the PDF should be amended
  # as it does not follow the conventions that the other specs use.
  - url: https://github.com/riscv-non-isa/riscv-elf-psabi-doc.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

#NOTE: Intrinsics needs to be broken into chapters as well.
  - url: https://github.com/riscv-non-isa/rvv-intrinsic-doc.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

    #  - url: ../../riscv-profiles
    #    branches: antora-refactor
    #    start_path: modules/profiles
    #    worktrees: true

    #  - url: ../../riscv-profiles
    #    branches: antora-refactor
    #    start_path: modules/rva23
    #    worktrees: true

    #  - url: ../../riscv-profiles
    #    branches: antora-refactor
    #    start_path: modules/rvb23
    #    worktrees: true

  #  - url: https://github.com/riscv/docs-dev-guide.git
  #    branches: [version25,antora-redo]
  #    start_page: ROOT::index.adoc
  #    start_path: /
  #    worktrees: true
  #    submodules: true

  #  - url: ./hardware-home
  #    start_page: ROOT::index.adoc

  #  - url: ./debug-trace-ras-home
  #    start_page: ROOT::index.adoc

  #  - url: ./platform-software-home
  #    start_page: ROOT::index.adoc


asciidoc:
  extensions:
  - asciidoctor-kroki
  - '@djencks/asciidoctor-mathjax'
  #- require: ./riscv-extensions/include-rewriter.js
  attributes:
    #Use this for local generation
    #kroki-server-url: http://localhost:8000
    #Thefollowing is required for GitHuib actions to work.
    kroki-server-url: http://localhost:9870
    kroki-fetch-diagram: true
    doctype: book
    experimental: ''
    icons: font
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    le: '&#8804;'
    ge: '&#8805;'
    ne: '&#8800;'
    approx: '&#8776;'
    inf: '&#8734;'
    circ: ○
    bullet: ∙
    times: ×
    csrname: 'envcfg'
    incexample: example$
    incimage: ../images/
    part-signifier: Chapter
    #sectnums: all
    #sectnumlevels: 5
    setanchors:
    #partnums: all
    #toc: ''
    toclevels: 5
    outlinelevels: 5
    source-highlighter: rouge
    pdf_url: ~
    multiple_pdfs: false
    pdf_list: ~
    fiximages: '../images'
    # Math and special characters
    vertical-ellipsis: '⋮'
    ellipsis: '…'
    check: '✓'
    prime: '′'
    pm: '±'
    rightarrow: '→'
    interpunct: '·'
    # Variables
    i: '_i_'
    u: '_u_'
    ra: '_ra_'
    reg_list: '_reg_list_'

# Temp disable for local build speedup. Re-enable for deployment.
runtime:
  fetch: true

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
  - require: './asam-extensions/asam-antora_extension.js'
    bibliography: true
    bibtex-order: "alphabetical"
    bibtex-style: "apa"
    bibtex-format: "asciidoc"
    bibtex-throw: false
  - require: ./riscv-extensions/antora_copy_files_extension.js
    target_sources:
    - url: 'https://github.com/riscv/riscv-isa-manual.git'
      branches: [v20250508,v20240411]
      #branches: ['main', '20250508', '20240411']
    source_dirs:
      # Copy all files from src/images/ to partials/
      - source: 'src/images'
        target: 'partials'
      # Copy only .adoc files from src/ to partials/
      - source: 'src'
        target: 'partials'
        extensions: ['.adoc']
      - source: 'src/example'
        target: 'examples'
        extensions: ['.s']
      - source: 'docs-resources/images'  # Add this for submodule images
        target: 'partials'
  - require: ./riscv-extensions/antora_include_rewriter.js
    target_sources:
      - url: 'https://github.com/riscv/riscv-isa-manual.git'
        #branches: ['main', '20250508', '20240411']
        branches: [v20250508,v20240411]
#    numbered_titles: true
#    section_number_style: "iso"
#  - '@antora/pdf-extension'
#     - '@antora/asciidoctor-bibtex'

  - require: ./riscv-extensions/nav_numbering_extension.js
    numbering_rules:  # Make sure this is at the same level as 'require'
        # priv module - v20240411 branch
        - module: priv
          branches: ['v20240411']
          chapters: {start: 5, end: 25}
          appendices: {start: 26, end: 28}

        # priv module - v20250508 branch
        - module: priv
          branches: ['v20250508']
          chapters: {start: 5, end: 24}
          appendices: {start: 25, end: 27}

        # priv module - main branch
        - module: priv
          branches: ['main']
          chapters: {start: 5, end: 24}
          appendices: {start: 25, end: 27}

        # unpriv module - v20240411 branch
        - module: unpriv
          branches: ['v20240411']
          chapters: {start: 5, end: 41}
          appendices: {start: 43, end: 46}

        # unpriv module - v20250508 branch
        - module: unpriv
          branches: ['v20250508']
          chapters: {start: 5, end: 41}
          appendices: {start: 42, end: 46}

        # unpriv module - main branch
        - module: unpriv
          branches: ['main']
          chapters: {start: 3, end: 18}
          appendices: {start: 19, end: 20}

        # AIA module - antora-refactor branch
        - component: aia
          module: ROOT
          branches: ['antora-refactor']
          chapters: { start: 6, end: 13}

        # IOMMU module - antora-refactor branch
        - component: iommu
          module: ROOT
          branches: ['antora-refactor']
          chapters: { start: 6, end: 14}

        # Server SOC - antora-refactor branch
        - component: soc
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 6}

        # Efficient Trace - antora-refactor-branch
        - component: techtrace
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 18}

        # Capacity & Bandwidth QoS
        - component: qos
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 11}

        # RERI
        - component: reri
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 7}

        # E-Trace encap
        - component: etrace
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 4, end: 7}

        # Semi-hosting
        - component: semihost
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 6}

        # BRS
        - component: brs
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 11}

        # RIMT
        - component: rimt
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 7, end: 10}

        # RPMI
        - component: rpmi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 6, end: 23}

        # SBI
        - component: sbi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 27}

        # UEFI
        - component: uefi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 3, end: 5}

        # psABI
        - component: abi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 3, end: 8}

        # Intrinsics
        - component: instrinsic
          module: ROOT
          changes: ['antora-refactor']
          chapters: {start: 4, end: 7}
          appendices: {start: 8, end: 47}

        # Plic
        - component: plic
          module: ROOT
          chapters: {start: 6, end: 13}

        # Rule without branch/tag filter - applies to all branches/tags
        - module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 1, end: 100}

  # Add section numbering (uses same config as nav-numbering)
  - require: ./riscv-extensions/section_numbering_extension.js
    numbering_rules:  # Make sure this is at the same level as 'require'
        # priv module - v20240411 branch
        - module: priv
          branches: ['v20240411']
          chapters: {start: 5, end: 25}
          appendices: {start: 26, end: 28}

        # priv module - v20250508 branch
        - module: priv
          branches: ['v20250508']
          chapters: {start: 5, end: 24}
          appendices: {start: 25, end: 27}

        # priv module - main branch
        - module: priv
          branches: ['main']
          chapters: {start: 5, end: 24}
          appendices: {start: 25, end: 27}

        # unpriv module - v20240411 branch
        - module: unpriv
          branches: ['v20240411']
          chapters: {start: 5, end: 41}
          appendices: {start: 43, end: 46}

        # unpriv module - v20250508 branch
        - module: unpriv
          branches: ['v20250508']
          chapters: {start: 5, end: 41}
          appendices: {start: 42, end: 46}

        # unpriv module - main branch
        - module: unpriv
          branches: ['main']
          chapters: {start: 3, end: 18}
          appendices: {start: 19, end: 20}

        # AIA module - antora-refactor branch
        - component: aia
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 6, end: 13}

        # IOMMU module - antora-refactor branch
        - component: iommu
          module: ROOT
          branches: ['antora-refactor']
          chapters: { start: 6, end: 14}

        # Server SOC - antora-refactor branch
        - component: soc
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 6}

        # Efficient Trace - antora-refactor-branch
        - component: techtrace
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 18}

        # Capacity & Bandwidth QoS
        - component: qos
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 3, end: 9}

        # RERI
        - component: reri
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 4, end: 5}

        # E-Trace encap
        - component: etrace
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 3, end: 6}

        # Semi-hosting
        - component: semihost
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 6}

        # BRS
        - component: brs
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 11}

        # RIMT
        - component: rimt
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 7, end: 10}

        # RPMI
        - component: rpmi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 7, end: 24}

        # SBI
        - component: sbi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 5, end: 27}

        # UEFI
        - component: uefi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 3, end: 5}

        # psABI
        - component: abi
          module: ROOT
          branches: ['antora-refactor']
          chapters: {start: 3, end: 8}

        # Intrinsics
        - component: instrinsic
          module: ROOT
          changes: ['antora-refactor']
          chapters: {start: 4, end: 7}
          appendices: {start: 8, end: 47}

        # Plic
        - component: plic
          module: ROOT
          chapters: {start: 6, end: 13}

        # Rule without branch/tag filter - applies to all branches/tags
        - module: ROOT
          branches: ['antora-refactor']
          chapters:
            start: 1
            end: 100


ui:
  bundle:
    #url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.2/ui-bundle.zip
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    #url: https://github.com/riscv-admin/riscv-antora-only-ui/releases/download/latest/ui-bundle.zip
    url: https://github.com/riscv-admin/riscv-antora-only-ui-dev/releases/download/latest/ui-bundle.zip
    #url: ../../riscv-antora-only-ui-dev/build/ui-bundle.zip

    snapshot: true
  #supplemental_files: ./supplimental-ui
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
      - index.html
      - ../index.html
  - path: .nojekyll
  - path: index.html
    contents: |
      <!DOCTYPE HTML>
      <html lang="en-US">
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=isa/">
              <!--<script type="text/javascript">
                  window.location.href = "http://example.com"
              </script>--->
              <title>Page Redirection</title>
          </head>
          <body>
              <!-- Note: don't tell people to `click` the link, just tell them that it is a link.
              If you are not redirected automatically, follow this <a href='isa/'>link to the ISA specification</a>.-->
          </body>
      </html>
  - path: ../index.html
    contents: |
      <!DOCTYPE HTML>
      <html lang="en-US">
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=reference/isa/">
              <!--<script type="text/javascript">
                  window.location.href = "http://example.com"
              </script>--->
              <title>Page Redirection</title>
          </head>
          <body>
              <!-- Note: don't tell people to `click` the link, just tell them that it is a link.
              If you are not redirected automatically, follow this <a href='reference/isa/'>link to the ISA specification</a>.-->
          </body>
      </html>
