site:
  title: RISC-V Ratified Specifications Library
  #url: https://docs.riscv.org
  url: https://riscv-admin.github.io/antora-dev.riscv.org/
  #start_page: isa:ROOT::index.adoc
  #keys:
  #  google_analytics: 'GTM-NXLCGZF4'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''



output:
  dir: ./build/reference

content:
  sources:
  - url: https://github.com/riscv/riscv-isa-manual.git
    branches: [v20250508,v20240411]
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv/riscv-profiles.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

#  - url: https://github.com/riscv-non-isa/e-trace-encap.git
#    branches: antora-refactor
    #tags: [v1.0]
#    start_page: ROOT::header.adoc
#    start_path: /

#  - url: https://github.com/riscv-non-isa/riscv-elf-psabi-doc.git
#    branches: antora-refactor
#    start_page: ROOT::introduction.adoc
#    start_path: /

#  - url: https://github.com/riscv-non-isa/riscv-cbqri.git
#    branches: antora-refactor
#    start_page: ROOT::intro.adoc
#    start_path: /

#  - url: https://github.com/riscv/riscv-aia.git
#    branches: antora-refactor
#    start_page: ROOT::intro.adoc
#    start_path: /

#  - url: https://github.com/riscv-non-isa/riscv-acpi-ffh.git
#    branches: antora-refactor
#    start_page: ROOT::contributors.adoc
#    start_path: /

#  - url: https://github.com/riscv-non-isa/riscv-iommu.git
#    branches: antora-refactor
#    start_page: ROOT::index.adoc
#    start_path: /

#  - url: https://github.com/riscv/riscv-plic-spec.git
#    branches: antora-refactor
#    start_page: ROOT::index.adoc
#    start_path: /

#  - url: https://github.com/riscv-non-isa/riscv-ras-eri.git
#    branches: antora-refactor
#    start_page: ROOT::index.adoc
#    start_path: /

#  - url: https://github.com/riscv-non-isa/riscv-semihosting.git
#    branches: antora-refactor
#    start_page: ROOT::index.adoc
#    start_path: /


asciidoc:
  extensions:
  - asciidoctor-kroki
  - '@djencks/asciidoctor-mathjax'
  attributes:
    doctype: book
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    le: '&#8804;'
    ge: '&#8805;'
    ne: '&#8800;'
    approx: '&#8776;'
    inf: '&#8734;'
    csrname: 'envcfg'
    incexample: example$
    incimage: ../images/
    part-signifier: Chapter
    sectnums: all
    sectnumlevels: 5
    setanchors:
    partnums: all
    #toc: ''
    toclevels: 5
    outlinelevels: 5
    source-highlighter: rouge
    pdf_url: ~
    multiple_pdfs: false
    pdf_list: ~

# Temp disable for local build speedup. Re-enable for deployment.
runtime:
  fetch: true

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
  - require: './asam-extensions/asam-antora_extension.js'
    bibliography: true
    bibtex-order: "alphabetical"
    bibtex-style: "apa"
    bibtex-format: "asciidoc"
    bibtex-throw: false
#    numbered_titles: true
#    section_number_style: "iso"
#  - '@antora/pdf-extension'
#     - '@antora/asciidoctor-bibtex'

ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    #url: https://github.com/riscv-admin/riscv-antora-only-ui/releases/download/latest/ui-bundle.zip
    url: https://github.com/riscv-admin/riscv-antora-only-ui-dev/releases/download/latest/ui-bundle.zip
    #url: ../../riscv-antora-only-ui-dev/build/ui-bundle.zip
    #url: ../../riscv-antora-only-ui/build/ui-bundle.zip

    snapshot: true
  #supplemental_files: ./supplemental-ui
  supplemental_files:
  - path: .nojekyll
  - path: index.html
    contents: |
      <!DOCTYPE HTML>
      <html lang="en-US">
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=isa/">
              <!--<script type="text/javascript">
                  window.location.href = "http://example.com"
              </script>--->
              <title>Page Redirection</title>
          </head>
          <body>
              <!-- Note: don't tell people to `click` the link, just tell them that it is a link.
              If you are not redirected automatically, follow this <a href='http://example.com'>link to example</a>.-->
          </body>
      </html>
  - path: ../index.html
    contents: |
      <!DOCTYPE HTML>
      <html lang="en-US">
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=reference/isa/">
              <!--<script type="text/javascript">
                  window.location.href = "http://example.com"
              </script>--->
              <title>Page Redirection</title>
          </head>
          <body>
              <!-- Note: don't tell people to `click` the link, just tell them that it is a link.
              If you are not redirected automatically, follow this <a href='http://example.com'>link to example</a>.-->
          </body>
      </html>
  - path: ui.yml
    contents: |
      static_files:
        - .nojekyll
        - index.html
        - ../index.html
