content:
  sources:
  - url: https://github.com/riscv/riscv-isa-manual.git
    branches: [v20250508,v20240411]
    start_page: ROOT::index.adoc
    start_path: /
    worktrees: true
    submodules: true
