content:
  sources:
  - url: https://github.com/riscv-non-isa/tg-nexus-trace.git
    branches: antora-refactor
    start_path: modules/ntrace

  - url: https://github.com/riscv-non-isa/tg-nexus-trace.git
    branches: antora-refactor
    start_path: modules/connectors

  - url: https://github.com/riscv-non-isa/tg-nexus-trace.git
    branches: antora-refactor
    start_path: modules/tci
