= RISC-V Specifications Library

Welcome to the RISC-V  Specifications Library. This site provides access to all ratified and under development RISC-V specifications.

[#about-riscv]
== About RISC-V

RISC-V (pronounced "risk-five") is an open standard instruction set architecture (ISA) based on established reduced instruction set computer (RISC) principles. These specifications are maintained by RISC-V International and represent the ratified, stable specifications for the RISC-V ecosystem.

For more information, visit https://riscv.org[riscv.org].

== RISC-V Ratified Specifications Library

[#core-architecture]
=== Core Architecture

// GENERATED-CARDS:isa

[#profiles]
=== Profiles

// GENERATED-CARDS:profile

[#platforms]
=== Platforms

// GENERATED-CARDS:platforms

[#hardware-specifications]
=== Hardware

// GENERATED-CARDS:hardware

[#debug-trace-and-ras]
=== Debug, Trace, and RAS

// GENERATED-CARDS:debug-trace-ras

[#platform-software]
=== Platform Software

// GENERATED-CARDS:platform-software

[#app-enablement]
=== Application Enablement

// GENERATED-CARDS:application-software

[#under-development]
== Under Development

// DEVELOPMENT-CARDS


