= RISC-V Specifications Library

Welcome to the RISC-V  Specifications Library. This site provides access to all ratified and under development RISC-V specifications.

[#about-riscv]
== About RISC-V

RISC-V (pronounced "risk-five") is an open standard instruction set architecture (ISA) based on established reduced instruction set computer (RISC) principles. These specifications are maintained by RISC-V International and represent the ratified, stable specifications for the RISC-V ecosystem.

For more information, visit https://riscv.org[riscv.org].

== RISC-V Ratified Specifications Library

[%collapsible%open]
.Core Architecture
====
// GENERATED-CARDS:isa
====

[%collapsible]
.Profiles
====
// GENERATED-CARDS:profile
====

[%collapsible]
.Platforms
====
// GENERATED-CARDS:platforms
====

[%collapsible]
.System Architecture
====
// GENERATED-CARDS:hardware
====

[%collapsible]
.Debug, Trace, and RAS
====
// GENERATED-CARDS:debug-trace-ras
====

[%collapsible]
.Platform Software
====
// GENERATED-CARDS:platform-software
====

[%collapsible]
.Application Enablement
====
// GENERATED-CARDS:application-software
====

== Under Development

Browse draft specifications currently under development by the RISC-V community. These documents are updated regularly. For the most current versions and specification status, use the link:https://riscv.github.io/adm-spec-dashboard/[RISC-V Specification Dashboard].

// DEVELOPMENT-CARDS


