name: Deploy Portal

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }} 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v4
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'yarn'
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1' # Not needed with a .ruby-version, .tool-versions or mise.toml
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install Antora Dependencies
      run: |
        cd antora
        gem install bundler
        bundle install
        npm install

    #- name: Install Docusaurus dependencies
    #  run: yarn install

    - name: Build Antora
      continue-on-error: true
      run: |
        cd antora 
        npx antora antora-playbook.yml --stacktrace
    
    - name: Manually Migrate Standalone PDFs
      continue-on-error: true
      run: |
        cd antora
        cp -a ./pdfs/. ./build/reference/
      
    #- name: Build Docusaurus
      # continue-on-error: true
    #  run: yarn build

    - name: Deploy to GitHub Pages
      # run: yarn deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: antora/build # The folder the action should deploy.

    - name: Upload Artifact Logs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Portal Snapshot
        path: ./antora/build/
